name: Deploy Github Pages

on:
  push:
    branches:
      - main
      - update-workflow
    paths-ignore:
      - 'api/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node_modules
        run: yarn --check-files --frozen-lockfile --non-interactive --production
      - name: Generate API
        run: |
          rm -rf api
          yarn adg generate api ./api --pretty
      - name: Commit
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'fix: update addresses'
          fetch: false
          default_author: github_actions
      - name: Minify json
        run: yarn adg minify 'api/**/*.json'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: api
      - uses: actions/deploy-pages@v2
        id: deployment
